import { z } from 'zod';
const source = z.object({
  url: z.url(),
  checkedOn: z.string(),
  status: z.enum(['verified', 'unverified']),
  note: z.string(),
});
export const AppSchema = z.object({
  slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  name: z.string().min(1),
  nameKo: z.string(),
  aliases: z.array(z.string()),
  domain: z.string(),
  category: z.string(),
  summary: z.string().min(10),
  officialUrl: z.url(),
  tags: z.array(z.string()),
  types: z.array(z.enum(['saas', 'desktop', 'local-first', 'open-source'])),
  platforms: z.array(z.string()),
  priceMonthly: z.number().nonnegative().nullable(),
  pricing: z.object({
    model: z.enum(['free', 'freemium', 'subscription', 'one-time', 'usage-based', 'contact-sales']),
    currency: z.string(),
    plan: z.string(),
    perSeat: z.boolean(),
    minimumSeats: z.number().int().positive(),
    billing: z.enum(['monthly', 'annual', 'one-time', 'free', 'unknown']),
    monthlyNative: z.number().nonnegative().nullable(),
    annualMonthlyNative: z.number().nonnegative().nullable(),
    oneTimeNative: z.number().nonnegative().nullable(),
    source,
    exchange: z.object({ rate: z.number(), date: z.string(), source: z.url() }).nullable(),
  }),
  verdict: z.enum(['yes', 'kinda', 'no']),
  verdictReason: z.string().min(30),
  checkedOn: z.string(),
  verification: z.literal('editorial'),
  scope: z.string().min(15),
  features: z.array(z.string()).min(3),
  difficulty: z.enum(['입문', '중급', '고급']),
  whatYouLose: z.array(z.string()).min(3),
  operations: z.array(z.string()),
  dependencies: z.array(z.string()),
  priorArt: z.array(
    z.object({
      name: z.string(),
      url: z.url(),
      license: z.string(),
      licenseUrl: z.url().nullable(),
      verified: z.boolean(),
    }),
  ),
  relatedSlugs: z.array(z.string()),
  prompt: z.string().min(500),
  promptVersion: z.string(),
  history: z.array(z.object({ version: z.string(), date: z.string(), note: z.string() })),
  notes: z.string(),
  faq: z.array(z.object({ q: z.string(), a: z.string() })).length(4),
  sources: z.array(source).min(1),
  published: z.boolean(),
});
export type App = z.infer<typeof AppSchema>;
